extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended

env:
  browser: false
  node: false

parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"

rules:
  indent:
    - warn
    - tab
    - SwitchCase: 1

  quotes:
    - warn
    - single

  semi:
    - error
    - always

  object-curly-spacing:
    - warn
    - always

  array-bracket-spacing:
    - warn
    - never
    - objectsInArrays: true
      arraysInArrays: true

  no-undef: off

  "@typescript-eslint/no-unused-vars":
    - warn
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"

  "@typescript-eslint/no-explicit-any": "off"
