import {
    adminDelete,
    adminPermissionsQuery,
    adminPermissionsUpdate,
    adminQueryMany,
    adminQueryOne,
    adminStream,
    adminUpdate,
    authInvite,
    authLoginFinish,
    authLoginStart,
    authOnboardFinish,
    authOnboardStart,
    authOnboardToken,
    authRegisterFinish,
    authRegisterStart,
    rosterAllowed,
    rosterPresentQuery,
    rosterPresentStream,
    rosterRecordAdd,
    rosterRecordDelete,
    rosterRecordQuery,
    rosterRecordStream,
    rosterRecordUpdate,
    rosterSwipe,
    rosterTotp,
    studentAdd,
    studentDelete,
    studentHours,
    studentList,
    studentQuery,
    studentStream,
    studentUpdate,
    telemetryFilterCreate,
    telemetryFilterUpdate,
    telemetryGet,
    telemetrySearch,
    telemetryStream,
} from "./hey/sdk.gen";

export default {
    "admin": {
        "delete": adminDelete,
        "query": { "many": adminQueryMany, "one": adminQueryOne },
        "update": adminUpdate,
        "stream": adminStream,
        "permissions": { "query": adminPermissionsQuery, "update": adminPermissionsUpdate },
    },
    "auth": {
        "login": { "start": authLoginStart, "finish": authLoginFinish },
        "invite": authInvite,
        "register": { "start": authRegisterStart, "finish": authRegisterFinish },
        "onboard": { "token": authOnboardToken, "start": authOnboardStart, "finish": authOnboardFinish },
    },
    "roster": {
        "swipe": rosterSwipe,
        "totp": rosterTotp,
        "present": { "query": rosterPresentQuery, "stream": rosterPresentStream },
        "record": {
            "delete": rosterRecordDelete,
            "query": rosterRecordQuery,
            "update": rosterRecordUpdate,
            "add": rosterRecordAdd,
            "stream": rosterRecordStream,
        },
        "allowed": rosterAllowed,
    },
    "student": {
        "list": studentList,
        "add": studentAdd,
        "stream": studentStream,
        "delete": studentDelete,
        "query": studentQuery,
        "update": studentUpdate,
        "hours": studentHours,
    },
    "telemetry": {
        "search": telemetrySearch,
        "get": telemetryGet,
        "filter": { "create": telemetryFilterCreate, "update": telemetryFilterUpdate },
        "stream": telemetryStream,
    },
} as const;
