import {
    authInvite,
    authLoginFinish,
    authLoginStart,
    authOnboardFinish,
    authOnboardStart,
    authOnboardToken,
    authRegisterFinish,
    authRegisterStart,
    rosterRecordAdd,
    rosterRecordDelete,
    rosterRecordQuery,
    rosterRecordStream,
    rosterRecordUpdate,
    rosterSwipe,
    rosterSwipesQuery,
    rosterSwipesStream,
    studentAdd,
    studentDelete,
    studentHours,
    studentList,
    studentQuery,
    studentStream,
    studentUpdate,
    telemetryGet,
    telemetryQuery,
    telemetryStream,
} from "./hey/sdk.gen";

export default {
    "auth": {
        "login": { "start": authLoginStart, "finish": authLoginFinish },
        "invite": authInvite,
        "register": { "start": authRegisterStart, "finish": authRegisterFinish },
        "onboard": { "token": authOnboardToken, "start": authOnboardStart, "finish": authOnboardFinish },
    },
    "roster": {
        "swipes": { "query": rosterSwipesQuery, "stream": rosterSwipesStream },
        "swipe": rosterSwipe,
        "record": {
            "delete": rosterRecordDelete,
            "query": rosterRecordQuery,
            "update": rosterRecordUpdate,
            "add": rosterRecordAdd,
            "stream": rosterRecordStream,
        },
    },
    "student": {
        "list": studentList,
        "add": studentAdd,
        "stream": studentStream,
        "delete": studentDelete,
        "query": studentQuery,
        "update": studentUpdate,
        "hours": studentHours,
    },
    "telemetry": { "get": telemetryGet, "stream": telemetryStream, "query": telemetryQuery },
} as const;
