/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Checks if the provided token is valid */
        get: operations["auth::validate"];
        put?: never;
        post?: never;
        /** @description Deauthorizes the provided token */
        delete: operations["auth::deauthorize"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Finishes the srp6a login process */
        post: operations["login::finish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Starts the srp6a login process */
        post: operations["login::start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Records a roster entry (login/logout) */
        post: operations["roster::record"];
        delete: operations["roster::clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Adds a new student */
        post: operations["student::add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Querys student hours */
        get: operations["student::query"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        HourType: "build" | "learning" | "demo" | "offseason";
        Hours: {
            /** Format: double */
            build: number;
            /** Format: double */
            demo: number;
            /** Format: double */
            learning: number;
            /** Format: double */
            offseason: number;
        };
        LoginFinishRequest: {
            a: string;
            m1: string;
        };
        LoginFinishResponse: {
            expires: string;
            m2: string;
            token: string;
        };
        LoginStartResponse: {
            b: string;
            salt: string;
        };
        /** @enum {string} */
        RosterAction: "login" | "logout";
        RosterRequest: {
            force?: boolean;
            id: string;
            kind: components["schemas"]["HourType"];
        };
        RosterResponse: {
            action: components["schemas"]["RosterAction"];
            denied: boolean;
        };
        StudentData: {
            first: string;
            hashed: string;
            id: string;
            last: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
    securitySchemes: {
        /** @description Token-based authentication. Provide the token in the Authorization header as 'Bearer <token>'. */
        Token: {
            type: "http";
            scheme: "bearer";
            bearerFormat: "token";
            description: "Token-based authentication. Provide the token in the Authorization header as 'Bearer <token>'.";
        };
    };
}
export type HourType = components['schemas']['HourType'];
export type Hours = components['schemas']['Hours'];
export type LoginFinishRequest = components['schemas']['LoginFinishRequest'];
export type LoginFinishResponse = components['schemas']['LoginFinishResponse'];
export type LoginStartResponse = components['schemas']['LoginStartResponse'];
export type RosterAction = components['schemas']['RosterAction'];
export type RosterRequest = components['schemas']['RosterRequest'];
export type RosterResponse = components['schemas']['RosterResponse'];
export type StudentData = components['schemas']['StudentData'];
export type SecuritySchemeToken = components['securitySchemes']['Token'];
export type $defs = Record<string, never>;
export interface operations {
    "auth::validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        security: {
            "Token": components['securitySchemes']["Token"] & {
                scopes: [
                ];
            };
        };
        requestBody?: never;
        responses: {
            /** @description Token is valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token is invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "auth::deauthorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        security: {
            "Token": components['securitySchemes']["Token"] & {
                scopes: [
                ];
            };
        };
        requestBody?: never;
        responses: {
            /** @description Token deauthorized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "login::finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        security?: never;
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginFinishRequest"];
            };
        };
        responses: {
            /** @description Login finished */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginFinishResponse"];
                };
            };
            /** @description Incorrect credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "login::start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        security?: never;
        requestBody?: never;
        responses: {
            /** @description Login started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginStartResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "roster::record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        security: {
            "Token": components['securitySchemes']["Token"] & {
                scopes: [
                ];
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RosterRequest"];
            };
        };
        responses: {
            /** @description Roster entry recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterResponse"];
                };
            };
            /** @description Invalid hour type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "roster::clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        security: {
            "Token": components['securitySchemes']["Token"] & {
                scopes: [
                ];
            };
        };
        requestBody?: never;
        responses: {
            /** @description Expired roster entries cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "student::add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        security: {
            "Token": components['securitySchemes']["Token"] & {
                scopes: [
                ];
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentData"];
            };
        };
        responses: {
            /** @description Student added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    "student::query": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The student's hashed ID */
                id: string;
            };
            cookie?: never;
        };
        security?: never;
        requestBody?: never;
        responses: {
            /** @description Student information fetched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hours"];
                };
            };
            /** @description No such student */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
