// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
    AuthInviteData,
    AuthInviteErrors,
    AuthInviteResponses,
    AuthLoginFinishData,
    AuthLoginFinishErrors,
    AuthLoginFinishResponses,
    AuthLoginStartData,
    AuthLoginStartErrors,
    AuthLoginStartResponses,
    AuthOnboardFinishData,
    AuthOnboardFinishErrors,
    AuthOnboardFinishResponses,
    AuthOnboardStartData,
    AuthOnboardStartErrors,
    AuthOnboardStartResponses,
    AuthOnboardTokenData,
    AuthOnboardTokenErrors,
    AuthOnboardTokenResponses,
    AuthRegisterFinishData,
    AuthRegisterFinishErrors,
    AuthRegisterFinishResponses,
    AuthRegisterStartData,
    AuthRegisterStartErrors,
    AuthRegisterStartResponses,
    RosterRecordAddData,
    RosterRecordAddErrors,
    RosterRecordAddResponses,
    RosterRecordDeleteData,
    RosterRecordDeleteErrors,
    RosterRecordDeleteResponses,
    RosterRecordQueryData,
    RosterRecordQueryErrors,
    RosterRecordQueryResponses,
    RosterRecordStreamData,
    RosterRecordStreamErrors,
    RosterRecordStreamResponses,
    RosterRecordUpdateData,
    RosterRecordUpdateErrors,
    RosterRecordUpdateResponses,
    RosterSwipeData,
    RosterSwipeErrors,
    RosterSwipeResponses,
    RosterSwipesQueryData,
    RosterSwipesQueryErrors,
    RosterSwipesQueryResponses,
    RosterSwipesStreamData,
    RosterSwipesStreamErrors,
    RosterSwipesStreamResponses,
    StudentAddData,
    StudentAddErrors,
    StudentAddResponses,
    StudentDeleteData,
    StudentDeleteErrors,
    StudentDeleteResponses,
    StudentHoursData,
    StudentHoursErrors,
    StudentHoursResponses,
    StudentListData,
    StudentListErrors,
    StudentListResponses,
    StudentQueryData,
    StudentQueryErrors,
    StudentQueryResponses,
    StudentStreamData,
    StudentStreamErrors,
    StudentStreamResponses,
    StudentUpdateData,
    StudentUpdateErrors,
    StudentUpdateResponses,
    TelemetryGetData,
    TelemetryGetErrors,
    TelemetryGetResponses,
    TelemetryQueryData,
    TelemetryQueryErrors,
    TelemetryQueryResponses,
    TelemetryStreamData,
    TelemetryStreamErrors,
    TelemetryStreamResponses,
} from "./types.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> =
    & Options2<TData, ThrowOnError>
    & {
        /**
         * You can provide a client instance returned by `createClient()` instead of
         * individual options. This might be also useful if you want to implement a
         * custom client.
         */
        client?: Client;
        /**
         * You can pass arbitrary values through the `meta` object. This can be
         * used to access values that aren't defined as part of the SDK function.
         */
        meta?: Record<string, unknown>;
    };

/**
 * LoginStart
 */
export const authLoginStart = <ThrowOnError extends boolean = false>(
    options: Options<AuthLoginStartData, ThrowOnError>,
) => (options.client ?? client).get<AuthLoginStartResponses, AuthLoginStartErrors, ThrowOnError>({
    url: "/auth/login",
    ...options,
});

/**
 * LoginFinish
 */
export const authLoginFinish = <ThrowOnError extends boolean = false>(
    options: Options<AuthLoginFinishData, ThrowOnError>,
) => (options.client ?? client).post<AuthLoginFinishResponses, AuthLoginFinishErrors, ThrowOnError>({
    url: "/auth/login",
    ...options,
    headers: {
        "Content-Type": "application/json; charset=utf-8",
        ...options.headers,
    },
});

/**
 * Invite
 */
export const authInvite = <ThrowOnError extends boolean = false>(options: Options<AuthInviteData, ThrowOnError>) =>
    (options.client ?? client).post<AuthInviteResponses, AuthInviteErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }, {
            in: "query",
            name: "token",
            type: "apiKey",
        }],
        url: "/auth/invite",
        ...options,
        headers: {
            "Content-Type": "application/json; charset=utf-8",
            ...options.headers,
        },
    });

/**
 * RegisterStart
 */
export const authRegisterStart = <ThrowOnError extends boolean = false>(
    options: Options<AuthRegisterStartData, ThrowOnError>,
) => (options.client ?? client).get<AuthRegisterStartResponses, AuthRegisterStartErrors, ThrowOnError>({
    url: "/auth/register",
    ...options,
});

/**
 * RegisterFinish
 */
export const authRegisterFinish = <ThrowOnError extends boolean = false>(
    options: Options<AuthRegisterFinishData, ThrowOnError>,
) => (options.client ?? client).post<AuthRegisterFinishResponses, AuthRegisterFinishErrors, ThrowOnError>({
    url: "/auth/register",
    ...options,
    headers: {
        "Content-Type": "application/json; charset=utf-8",
        ...options.headers,
    },
});

/**
 * OnboardToken
 */
export const authOnboardToken = <ThrowOnError extends boolean = false>(
    options?: Options<AuthOnboardTokenData, ThrowOnError>,
) => (options?.client ?? client).post<AuthOnboardTokenResponses, AuthOnboardTokenErrors, ThrowOnError>({
    url: "/auth/onboard/token",
    ...options,
});

/**
 * OnboardStart
 */
export const authOnboardStart = <ThrowOnError extends boolean = false>(
    options: Options<AuthOnboardStartData, ThrowOnError>,
) => (options.client ?? client).get<AuthOnboardStartResponses, AuthOnboardStartErrors, ThrowOnError>({
    url: "/auth/onboard",
    ...options,
});

/**
 * OnboardFinish
 */
export const authOnboardFinish = <ThrowOnError extends boolean = false>(
    options: Options<AuthOnboardFinishData, ThrowOnError>,
) => (options.client ?? client).post<AuthOnboardFinishResponses, AuthOnboardFinishErrors, ThrowOnError>({
    url: "/auth/onboard",
    ...options,
    headers: {
        "Content-Type": "application/json; charset=utf-8",
        ...options.headers,
    },
});

/**
 * SwipesQuery
 */
export const rosterSwipesQuery = <ThrowOnError extends boolean = false>(
    options?: Options<RosterSwipesQueryData, ThrowOnError>,
) => (options?.client ?? client).get<RosterSwipesQueryResponses, RosterSwipesQueryErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/roster/swipe",
    ...options,
});

/**
 * Swipe
 */
export const rosterSwipe = <ThrowOnError extends boolean = false>(options: Options<RosterSwipeData, ThrowOnError>) =>
    (options.client ?? client).post<RosterSwipeResponses, RosterSwipeErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }, {
            in: "query",
            name: "token",
            type: "apiKey",
        }],
        url: "/roster/swipe",
        ...options,
        headers: {
            "Content-Type": "application/json; charset=utf-8",
            ...options.headers,
        },
    });

/**
 * SwipesStream
 */
export const rosterSwipesStream = <ThrowOnError extends boolean = false>(
    options?: Options<RosterSwipesStreamData, ThrowOnError>,
) => (options?.client ?? client).sse.get<RosterSwipesStreamResponses, RosterSwipesStreamErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/roster/swipe/stream",
    ...options,
});

/**
 * RecordDelete
 */
export const rosterRecordDelete = <ThrowOnError extends boolean = false>(
    options: Options<RosterRecordDeleteData, ThrowOnError>,
) => (options.client ?? client).delete<RosterRecordDeleteResponses, RosterRecordDeleteErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/roster",
    ...options,
    headers: {
        "Content-Type": "application/json; charset=utf-8",
        ...options.headers,
    },
});

/**
 * RecordQuery
 */
export const rosterRecordQuery = <ThrowOnError extends boolean = false>(
    options?: Options<RosterRecordQueryData, ThrowOnError>,
) => (options?.client ?? client).get<RosterRecordQueryResponses, RosterRecordQueryErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/roster",
    ...options,
});

/**
 * RecordUpdate
 */
export const rosterRecordUpdate = <ThrowOnError extends boolean = false>(
    options: Options<RosterRecordUpdateData, ThrowOnError>,
) => (options.client ?? client).patch<RosterRecordUpdateResponses, RosterRecordUpdateErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/roster",
    ...options,
    headers: {
        "Content-Type": "application/json; charset=utf-8",
        ...options.headers,
    },
});

/**
 * RecordAdd
 */
export const rosterRecordAdd = <ThrowOnError extends boolean = false>(
    options: Options<RosterRecordAddData, ThrowOnError>,
) => (options.client ?? client).post<RosterRecordAddResponses, RosterRecordAddErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/roster",
    ...options,
    headers: {
        "Content-Type": "application/json; charset=utf-8",
        ...options.headers,
    },
});

/**
 * RecordStream
 */
export const rosterRecordStream = <ThrowOnError extends boolean = false>(
    options?: Options<RosterRecordStreamData, ThrowOnError>,
) => (options?.client ?? client).sse.get<RosterRecordStreamResponses, RosterRecordStreamErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/roster/stream",
    ...options,
});

/**
 * List
 */
export const studentList = <ThrowOnError extends boolean = false>(options?: Options<StudentListData, ThrowOnError>) =>
    (options?.client ?? client).get<StudentListResponses, StudentListErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }, {
            in: "query",
            name: "token",
            type: "apiKey",
        }],
        url: "/student",
        ...options,
    });

/**
 * Add
 */
export const studentAdd = <ThrowOnError extends boolean = false>(options: Options<StudentAddData, ThrowOnError>) =>
    (options.client ?? client).post<StudentAddResponses, StudentAddErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }, {
            in: "query",
            name: "token",
            type: "apiKey",
        }],
        url: "/student",
        ...options,
        headers: {
            "Content-Type": "application/json; charset=utf-8",
            ...options.headers,
        },
    });

/**
 * Stream
 */
export const studentStream = <ThrowOnError extends boolean = false>(
    options?: Options<StudentStreamData, ThrowOnError>,
) => (options?.client ?? client).sse.get<StudentStreamResponses, StudentStreamErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/student/stream",
    ...options,
});

/**
 * Delete
 */
export const studentDelete = <ThrowOnError extends boolean = false>(
    options: Options<StudentDeleteData, ThrowOnError>,
) => (options.client ?? client).delete<StudentDeleteResponses, StudentDeleteErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/student/{id_hashed}",
    ...options,
});

/**
 * Query
 */
export const studentQuery = <ThrowOnError extends boolean = false>(options: Options<StudentQueryData, ThrowOnError>) =>
    (options.client ?? client).get<StudentQueryResponses, StudentQueryErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }, {
            in: "query",
            name: "token",
            type: "apiKey",
        }],
        url: "/student/{id_hashed}",
        ...options,
    });

/**
 * Update
 */
export const studentUpdate = <ThrowOnError extends boolean = false>(
    options: Options<StudentUpdateData, ThrowOnError>,
) => (options.client ?? client).patch<StudentUpdateResponses, StudentUpdateErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/student/{id_hashed}",
    ...options,
    headers: {
        "Content-Type": "application/json; charset=utf-8",
        ...options.headers,
    },
});

/**
 * Hours
 */
export const studentHours = <ThrowOnError extends boolean = false>(options: Options<StudentHoursData, ThrowOnError>) =>
    (options.client ?? client).get<StudentHoursResponses, StudentHoursErrors, ThrowOnError>({
        url: "/student/{id_hashed}/hours",
        ...options,
    });

/**
 * Get
 */
export const telemetryGet = <ThrowOnError extends boolean = false>(options: Options<TelemetryGetData, ThrowOnError>) =>
    (options.client ?? client).get<TelemetryGetResponses, TelemetryGetErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }, {
            in: "query",
            name: "token",
            type: "apiKey",
        }],
        url: "/telemetry",
        ...options,
    });

/**
 * Stream
 */
export const telemetryStream = <ThrowOnError extends boolean = false>(
    options?: Options<TelemetryStreamData, ThrowOnError>,
) => (options?.client ?? client).sse.get<TelemetryStreamResponses, TelemetryStreamErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/telemetry/stream",
    ...options,
});

/**
 * Query
 */
export const telemetryQuery = <ThrowOnError extends boolean = false>(
    options: Options<TelemetryQueryData, ThrowOnError>,
) => (options.client ?? client).get<TelemetryQueryResponses, TelemetryQueryErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }, {
        in: "query",
        name: "token",
        type: "apiKey",
    }],
    url: "/telemetry/{event_type}",
    ...options,
});
