// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * Admin
 */
export type Admin = {
    id: string;
    sid_hashed: string | null;
    username: string;
};

/**
 * AdminDelete
 */
export type AdminDelete = {
    admin_id: string;
    target: Admin;
};

/**
 * AdminDeleteRequest
 */
export type AdminDeleteRequest = {
    admin_id: string;
};

/**
 * AdminEdit
 */
export type AdminEdit = {
    /**
     * Corresponds to the admin who performed the edit
     */
    admin_id: string;
    old: Admin;
    id: string;
    sid_hashed?: string | null;
    username?: string;
};

/**
 * AdminIdFilter
 */
export type AdminIdFilter = {
    /**
     * List of admin IDs to filter by
     *
     * This will correspond to the admin who performed or otherwise authorized
     * or triggered the event.
     *
     * This will NOT correspond to the admin that was acted upon, if any,
     * unless, of course, it is the same as the acting admin.
     */
    admin_id: Array<string>;
};

/**
 * AdminLogin
 */
export type AdminLogin = {
    id: string;
};

/**
 * AdminOperationFilter
 */
export type AdminOperationFilter = {
    /**
     * Corresponds to the admin who performed the operation
     */
    admin_id: Array<string>;
    /**
     * Corresponds to the admin acted upon.
     */
    target_id: Array<string>;
};

/**
 * AdminQueryManyResponse
 */
export type AdminQueryManyResponse = {
    admins: {
        [key: string]: Admin;
    };
};

/**
 * Claims
 */
export type Claims = {
    sub: string;
    exp: number;
    perms: Permissions;
    k1e: string;
    username: string;
};

/**
 * Deletion_Admin
 */
export type DeletionAdmin = {
    pkey: string;
};

/**
 * Deletion_Record
 */
export type DeletionRecord = {
    pkey: string;
};

/**
 * Deletion_Student
 */
export type DeletionStudent = {
    pkey: string;
};

export type Event =
    | ({
        event?: "admin_login";
    } & EventAdminLogin)
    | ({
        event?: "admin_delete";
    } & EventAdminDelete)
    | ({
        event?: "admin_edit";
    } & EventAdminEdit)
    | ({
        event?: "permission_edit";
    } & EventPermissionEdit)
    | ({
        event?: "invite_add";
    } & EventInviteAdd)
    | ({
        event?: "invite_use";
    } & EventInviteUse)
    | ({
        event?: "student_add";
    } & EventStudentAdd)
    | ({
        event?: "student_delete";
    } & EventStudentDelete)
    | ({
        event?: "student_edit";
    } & EventStudentEdit)
    | ({
        event?: "record_add";
    } & EventRecordAdd)
    | ({
        event?: "record_delete";
    } & EventRecordDelete)
    | ({
        event?: "record_edit";
    } & EventRecordEdit)
    | ({
        event?: "student_login";
    } & EventStudentLogin)
    | ({
        event?: "student_logout";
    } & EventStudentLogout);

export type EventTypeFilter =
    | ({
        event?: "admin_delete";
    } & EventTypeFilterAdminDelete)
    | ({
        event?: "admin_edit";
    } & EventTypeFilterAdminEdit)
    | ({
        event?: "permission_edit";
    } & EventTypeFilterPermissionEdit)
    | ({
        event?: "admin_login";
    } & EventTypeFilterAdminLogin)
    | ({
        event?: "invite_add";
    } & EventTypeFilterInviteAdd)
    | ({
        event?: "invite_use";
    } & EventTypeFilterInviteUse)
    | ({
        event?: "record_add";
    } & EventTypeFilterRecordAdd)
    | ({
        event?: "record_delete";
    } & EventTypeFilterRecordDelete)
    | ({
        event?: "record_edit";
    } & EventTypeFilterRecordEdit)
    | ({
        event?: "student_add";
    } & EventTypeFilterStudentAdd)
    | ({
        event?: "student_delete";
    } & EventTypeFilterStudentDelete)
    | ({
        event?: "student_edit";
    } & EventTypeFilterStudentEdit)
    | ({
        event?: "student_login";
    } & EventTypeFilterStudentLogin)
    | ({
        event?: "student_logout";
    } & EventTypeFilterStudentLogout);

export type EventTypeFilterAdminDelete = {
    event: "admin_delete";
} & AdminOperationFilter;

export type EventTypeFilterAdminEdit = {
    event: "admin_edit";
} & AdminOperationFilter;

export type EventTypeFilterAdminLogin = {
    event: "admin_login";
} & AdminIdFilter;

export type EventTypeFilterInviteAdd = {
    event: "invite_add";
} & AdminIdFilter;

export type EventTypeFilterInviteUse = {
    event: "invite_use";
} & InviteUseFilter;

export type EventTypeFilterPermissionEdit = {
    event: "permission_edit";
} & AdminOperationFilter;

export type EventTypeFilterRecordAdd = {
    event: "record_add";
} & AdminIdFilter;

export type EventTypeFilterRecordDelete = {
    event: "record_delete";
} & AdminIdFilter;

export type EventTypeFilterRecordEdit = {
    event: "record_edit";
} & AdminIdFilter;

export type EventTypeFilterStudentAdd = {
    event: "student_add";
} & AdminIdFilter;

export type EventTypeFilterStudentDelete = {
    event: "student_delete";
} & AdminIdFilter;

export type EventTypeFilterStudentEdit = {
    event: "student_edit";
} & AdminIdFilter;

export type EventTypeFilterStudentLogin = {
    event: "student_login";
} & StudentActionFilter;

export type EventTypeFilterStudentLogout = {
    event: "student_logout";
} & StudentActionFilter;

export type EventAdminDelete = {
    event: "admin_delete";
} & AdminDelete;

export type EventAdminEdit = {
    event: "admin_edit";
} & AdminEdit;

export type EventAdminLogin = {
    event: "admin_login";
} & AdminLogin;

export type EventInviteAdd = {
    event: "invite_add";
} & InviteAdd;

export type EventInviteUse = {
    event: "invite_use";
} & InviteUse;

export type EventPermissionEdit = {
    event: "permission_edit";
} & PermissionEdit;

export type EventRecordAdd = {
    event: "record_add";
} & RecordAdd;

export type EventRecordDelete = {
    event: "record_delete";
} & RecordDelete;

export type EventRecordEdit = {
    event: "record_edit";
} & RecordEdit;

export type EventStudentAdd = {
    event: "student_add";
} & StudentAdd;

export type EventStudentDelete = {
    event: "student_delete";
} & StudentDelete;

export type EventStudentEdit = {
    event: "student_edit";
} & StudentEdit;

export type EventStudentLogin = {
    event: "student_login";
} & StudentLogin;

export type EventStudentLogout = {
    event: "student_logout";
} & StudentLogout;

/**
 * FilterCounted
 */
export type FilterCounted = {
    /**
     * Number of telemetry events to retrieve.
     *
     * This will correspond to the events fetched from the database
     * PRECEDING ALL OTHER FILTERING. In other words, you are NOT
     * guaranteed to receive `count` events in the response, as the
     * filtering is done after fetching.
     *
     * You will not recieve an empty response unless there are no events
     * matching your filters.
     *
     * Maximum: 100
     */
    count?: number;
    /**
     * Number of telemetry events to skip. Will be sorted by timestamp
     * descending.
     *
     * Default: 0
     */
    skip?: number;
};

/**
 * FilterDateRange
 */
export type FilterDateRange = {
    /**
     * Start time for telemetry events
     */
    after: string;
    /**
     * End time for telemetry events
     *
     * Default: now
     */
    before?: string;
};

export type HourType = "build" | "learning" | "demo" | "offseason";

/**
 * InviteAdd
 */
export type InviteAdd = {
    admin_id: string;
};

/**
 * InviteRequest
 */
export type InviteRequest = {
    /**
     * The hashed student ID to associate with this invite, if any.
     */
    sid_hashed?: string | null;
    /**
     * Initial permissions to grant the user
     */
    permissions: Permissions & unknown;
};

/**
 * InviteResponse
 */
export type InviteResponse = {
    /**
     * Temporary key to encrypt k1. Do NOT share this
     */
    k2: string;
    /**
     * Invite token. This goes in the link
     */
    token: string;
};

/**
 * InviteUse
 */
export type InviteUse = {
    inviter_id: string;
    invitee_id: string;
};

/**
 * InviteUseFilter
 */
export type InviteUseFilter = {
    /**
     * List of inviter IDs to filter by
     */
    inviter_id: Array<string>;
    /**
     * List of invitee IDs to filter by
     */
    invitee_id: Array<string>;
};

/**
 * LoginFinishRequest
 */
export type LoginFinishRequest = {
    session: string;
    a: string;
    m1: string;
};

/**
 * LoginFinishResponse
 */
export type LoginFinishResponse = {
    jwt: string;
    claims: Claims;
};

/**
 * LoginStartResponse
 */
export type LoginStartResponse = {
    session: string;
    salt: string;
    b: string;
};

/**
 * OnboardFinishRequest
 */
export type OnboardFinishRequest = {
    students: Array<Student>;
    token: string;
    k1e: string;
    username: string;
    v: string;
    s: string;
};

/**
 * PartialAdmin
 */
export type PartialAdmin = {
    id: string;
    sid_hashed?: string | null;
    username?: string;
};

/**
 * PartialRecord
 */
export type PartialRecord = {
    id: string;
    sid_hashed?: string;
    hour_type?: HourType;
    sign_in?: string;
    sign_out?: string | null;
};

/**
 * PartialStudent
 */
export type PartialStudent = {
    id_hashed: string;
    id?: string;
    first?: string;
    last?: string;
};

/**
 * PermissionEdit
 */
export type PermissionEdit = {
    /**
     * Corresponds to the admin who performed the edit
     */
    admin_id: string;
    /**
     * Corresponds to the admin whose permissions were edited
     */
    target_id: string;
    old: Permissions;
    new: Permissions;
};

/**
 * Permissions
 */
export type Permissions = {
    student_add: boolean;
    student_view: boolean;
    student_edit: boolean;
    student_delete: boolean;
    admin_invite: boolean;
    admin_delete: boolean;
    telemetry: boolean;
    hours_view: boolean;
    hours_edit: boolean;
    roster: boolean;
    admin_edit: boolean;
    admin_view: boolean;
};

/**
 * PresentResponse
 */
export type PresentResponse = {
    present: Array<string>;
    absent: Array<string>;
};

export type QueryFilter =
    | ({
        query_type?: "counted";
    } & QueryFilterCounted)
    | ({
        query_type?: "date_range";
    } & QueryFilterDateRange);

export type QueryFilterCounted = {
    query_type: "counted";
} & FilterCounted;

export type QueryFilterDateRange = {
    query_type: "date_range";
} & FilterDateRange;

/**
 * Record
 */
export type Record = {
    id: string;
    sid_hashed: string;
    hour_type: HourType;
    sign_in: string;
    sign_out: string | null;
};

/**
 * RecordAdd
 */
export type RecordAdd = {
    admin_id: string;
    id: string;
    sid_hashed: string;
    hour_type: HourType;
    sign_in: string;
    sign_out: string | null;
};

/**
 * RecordDelete
 */
export type RecordDelete = {
    admin_id: string;
    id: string;
    sid_hashed: string;
    hour_type: HourType;
    sign_in: string;
    sign_out: string | null;
};

/**
 * RecordEdit
 */
export type RecordEdit = {
    admin_id: string;
    old: Record;
    id: string;
    sid_hashed?: string;
    hour_type?: HourType;
    sign_in?: string;
    sign_out?: string | null;
};

/**
 * RegisterFinishRequest
 */
export type RegisterFinishRequest = {
    token: string;
    k1e: string;
    username: string;
    v: string;
    s: string;
};

/**
 * RegisterStartResponse
 */
export type RegisterStartResponse = {
    k2: string;
};

export type ReplicationAdmin =
    | ({
        operation?: "INSERT";
    } & ReplicationAdminInsert)
    | ({
        operation?: "UPDATE";
    } & ReplicationAdminUpdate)
    | ({
        operation?: "DELETE";
    } & ReplicationAdminDelete);

export type ReplicationAdminDelete = {
    operation: "DELETE";
} & DeletionAdmin;

export type ReplicationAdminInsert = {
    operation: "INSERT";
} & Admin;

export type ReplicationAdminUpdate = {
    operation: "UPDATE";
} & PartialAdmin;

export type ReplicationRecord =
    | ({
        operation?: "INSERT";
    } & ReplicationRecordInsert)
    | ({
        operation?: "UPDATE";
    } & ReplicationRecordUpdate)
    | ({
        operation?: "DELETE";
    } & ReplicationRecordDelete);

export type ReplicationRecordDelete = {
    operation: "DELETE";
} & DeletionRecord;

export type ReplicationRecordInsert = {
    operation: "INSERT";
} & Record;

export type ReplicationRecordUpdate = {
    operation: "UPDATE";
} & PartialRecord;

export type ReplicationStudent =
    | ({
        operation?: "INSERT";
    } & ReplicationStudentInsert)
    | ({
        operation?: "UPDATE";
    } & ReplicationStudentUpdate)
    | ({
        operation?: "DELETE";
    } & ReplicationStudentDelete);

export type ReplicationStudentDelete = {
    operation: "DELETE";
} & DeletionStudent;

export type ReplicationStudentInsert = {
    operation: "INSERT";
} & Student;

export type ReplicationStudentUpdate = {
    operation: "UPDATE";
} & PartialStudent;

/**
 * RosterCreateRequest
 */
export type RosterCreateRequest = {
    sid_hashed: string;
    kind: HourType;
    time_in: string;
    /**
     * Must be after and on the same day as time_in (in server's local time)
     */
    time_out?: string | null;
};

/**
 * RosterCreateResponse
 */
export type RosterCreateResponse = {
    entry_id: string;
};

/**
 * RosterDeleteRequest
 */
export type RosterDeleteRequest = {
    entry_id: string;
};

/**
 * RosterQueryMany
 */
export type RosterQueryMany = {
    records: {
        [key: string]: Record;
    };
};

export type RosterQueryResponse =
    | ({
        quantity?: "Many";
    } & RosterQueryResponseMany)
    | ({
        quantity?: "One";
    } & RosterQueryResponseOne);

export type RosterQueryResponseMany = {
    quantity: "Many";
} & RosterQueryMany;

export type RosterQueryResponseOne = {
    quantity: "One";
} & Record;

/**
 * Student
 */
export type Student = {
    id: string;
    first: string;
    last: string;
    id_hashed: string;
};

/**
 * StudentActionFilter
 */
export type StudentActionFilter = {
    /**
     * List of admin IDs to filter by
     */
    admin_id: Array<string>;
    /**
     * List of student hashed SIDs to filter by
     */
    sid_hashed: Array<string>;
};

/**
 * StudentAdd
 */
export type StudentAdd = {
    admin_id: string;
    id: string;
    first: string;
    last: string;
    id_hashed: string;
};

/**
 * StudentDelete
 */
export type StudentDelete = {
    admin_id: string;
    id: string;
    first: string;
    last: string;
    id_hashed: string;
};

/**
 * StudentEdit
 */
export type StudentEdit = {
    admin_id: string;
    old: Student;
    id_hashed: string;
    id?: string;
    first?: string;
    last?: string;
};

/**
 * StudentHoursResponse
 */
export type StudentHoursResponse = {
    build: number;
    learning: number;
    demo: number;
    offseason: number;
};

/**
 * StudentListResponse
 */
export type StudentListResponse = {
    students: Array<Student>;
};

/**
 * StudentLogin
 */
export type StudentLogin = {
    sid_hashed: string;
    record_id: string;
    admin_id: string;
};

/**
 * StudentLogout
 */
export type StudentLogout = {
    sid_hashed: string;
    record_id: string;
    admin_id: string;
};

/**
 * StudentUpdateRequest
 */
export type StudentUpdateRequest = {
    id?: string | null;
    first?: string | null;
    last?: string | null;
};

export type SwipeAction = "login" | "logout";

export type SwipeFallthrough = "denied" | "ignored";

/**
 * SwipeRequest
 */
export type SwipeRequest = {
    /**
     * AKA: admin's ID, TOTP `account_name`
     */
    issuer: string;
    totp: string;
    sid_hashed: string;
    kind: HourType;
    force?: boolean;
    action?: (SwipeAction & unknown) | null;
};

export type SwipeResponse = SwipeAction | SwipeFallthrough;

/**
 * TOTPRequest
 */
export type TotpRequest = {
    hour_type: HourType;
};

/**
 * TOTPResponse
 *
 * TOTP Generator Data
 *
 * The following parameters are assumed:
 * * Algorithm: SHA1
 * * Digits: 6
 * * Step: 30 seconds
 * * Skew: 1 interval
 */
export type TotpResponse = {
    /**
     * Base32-encoded TOTP secret
     */
    secret: string;
};

/**
 * TelemetryEvent
 */
export type TelemetryEvent = {
    id: string;
    event: Event;
    timestamp: string;
};

/**
 * TelemetryQueryRequest
 */
export type TelemetryQueryRequest = {
    event_type?: EventTypeFilter;
    query: QueryFilter;
};

/**
 * TelemetryResponse
 */
export type TelemetryResponse = {
    events: Array<TelemetryEvent>;
};

export type AdminDeleteData = {
    body: AdminDeleteRequest;
    path?: never;
    query?: never;
    url: "/admin";
};

export type AdminDeleteErrors = {
    401: string;
    403: string;
    /**
     * Admin with the given ID does not exist
     */
    404: string;
    500: string;
};

export type AdminDeleteError = AdminDeleteErrors[keyof AdminDeleteErrors];

export type AdminDeleteResponses = {
    200: Admin;
};

export type AdminDeleteResponse = AdminDeleteResponses[keyof AdminDeleteResponses];

export type AdminQueryManyData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/admin";
};

export type AdminQueryManyErrors = {
    401: string;
    403: string;
    500: string;
};

export type AdminQueryManyError = AdminQueryManyErrors[keyof AdminQueryManyErrors];

export type AdminQueryManyResponses = {
    200: AdminQueryManyResponse;
};

export type AdminQueryManyResponse2 = AdminQueryManyResponses[keyof AdminQueryManyResponses];

export type AdminUpdateData = {
    body: PartialAdmin;
    path?: never;
    query?: never;
    url: "/admin";
};

export type AdminUpdateErrors = {
    401: string;
    403: string;
    /**
     * Admin with the given ID does not exist
     */
    404: string;
    500: string;
};

export type AdminUpdateError = AdminUpdateErrors[keyof AdminUpdateErrors];

export type AdminUpdateResponses = {
    200: Admin;
};

export type AdminUpdateResponse = AdminUpdateResponses[keyof AdminUpdateResponses];

export type AdminQueryOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/admin/{id}";
};

export type AdminQueryOneErrors = {
    401: string;
    403: string;
    /**
     * Admin with the given ID does not exist
     */
    404: string;
    500: string;
};

export type AdminQueryOneError = AdminQueryOneErrors[keyof AdminQueryOneErrors];

export type AdminQueryOneResponses = {
    200: Admin;
};

export type AdminQueryOneResponse = AdminQueryOneResponses[keyof AdminQueryOneResponses];

export type AdminStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/admin/stream";
};

export type AdminStreamErrors = {
    401: string;
    403: string;
    /**
     * Admin with the given ID does not exist
     */
    404: string;
    500: string;
};

export type AdminStreamError = AdminStreamErrors[keyof AdminStreamErrors];

export type AdminStreamResponses = {
    200: Array<ReplicationAdmin>;
};

export type AdminStreamResponse = AdminStreamResponses[keyof AdminStreamResponses];

export type AdminPermissionsQueryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/admin/{id}/permissions";
};

export type AdminPermissionsQueryErrors = {
    401: string;
    403: string;
    /**
     * Admin with the given ID does not exist
     */
    404: string;
    500: string;
};

export type AdminPermissionsQueryError = AdminPermissionsQueryErrors[keyof AdminPermissionsQueryErrors];

export type AdminPermissionsQueryResponses = {
    200: Permissions;
};

export type AdminPermissionsQueryResponse = AdminPermissionsQueryResponses[keyof AdminPermissionsQueryResponses];

export type AdminPermissionsUpdateData = {
    body: Permissions;
    path: {
        id: string;
    };
    query?: never;
    url: "/admin/{id}/permissions";
};

export type AdminPermissionsUpdateErrors = {
    401: string;
    403: string;
    /**
     * Admin with the given ID does not exist
     */
    404: string;
    500: string;
};

export type AdminPermissionsUpdateError = AdminPermissionsUpdateErrors[keyof AdminPermissionsUpdateErrors];

export type AdminPermissionsUpdateResponses = {
    200: unknown;
};

export type AuthLoginStartData = {
    body?: never;
    path?: never;
    query: {
        username: string;
    };
    url: "/auth/login";
};

export type AuthLoginStartErrors = {
    404: string;
    500: string;
};

export type AuthLoginStartError = AuthLoginStartErrors[keyof AuthLoginStartErrors];

export type AuthLoginStartResponses = {
    200: LoginStartResponse;
};

export type AuthLoginStartResponse = AuthLoginStartResponses[keyof AuthLoginStartResponses];

export type AuthLoginFinishData = {
    body: LoginFinishRequest;
    path?: never;
    query?: never;
    url: "/auth/login";
};

export type AuthLoginFinishErrors = {
    /**
     * Invalid hex encoding for `a` or `m1`
     */
    400: string;
    401: string;
    500: string;
};

export type AuthLoginFinishError = AuthLoginFinishErrors[keyof AuthLoginFinishErrors];

export type AuthLoginFinishResponses = {
    200: LoginFinishResponse;
};

export type AuthLoginFinishResponse = AuthLoginFinishResponses[keyof AuthLoginFinishResponses];

export type AuthInviteData = {
    body: InviteRequest;
    path?: never;
    query?: never;
    url: "/auth/invite";
};

export type AuthInviteErrors = {
    401: string;
    403: string;
    500: string;
};

export type AuthInviteError = AuthInviteErrors[keyof AuthInviteErrors];

export type AuthInviteResponses = {
    200: InviteResponse;
};

export type AuthInviteResponse = AuthInviteResponses[keyof AuthInviteResponses];

export type AuthRegisterStartData = {
    body?: never;
    path?: never;
    query: {
        key: string;
    };
    url: "/auth/register";
};

export type AuthRegisterStartErrors = {
    401: string;
    500: string;
};

export type AuthRegisterStartError = AuthRegisterStartErrors[keyof AuthRegisterStartErrors];

export type AuthRegisterStartResponses = {
    200: RegisterStartResponse;
};

export type AuthRegisterStartResponse = AuthRegisterStartResponses[keyof AuthRegisterStartResponses];

export type AuthRegisterFinishData = {
    body: RegisterFinishRequest;
    path?: never;
    query?: never;
    url: "/auth/register";
};

export type AuthRegisterFinishErrors = {
    /**
     * Invalid hex encoding for `v` or `s`
     */
    400: string;
    401: string;
    500: string;
};

export type AuthRegisterFinishError = AuthRegisterFinishErrors[keyof AuthRegisterFinishErrors];

export type AuthRegisterFinishResponses = {
    200: unknown;
};

export type AuthOnboardTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/auth/onboard/token";
};

export type AuthOnboardTokenErrors = {
    401: string;
    500: string;
};

export type AuthOnboardTokenError = AuthOnboardTokenErrors[keyof AuthOnboardTokenErrors];

export type AuthOnboardTokenResponses = {
    200: unknown;
};

export type AuthOnboardStartData = {
    body?: never;
    headers: {
        /**
         * The setup token obtained from /auth/onboard/token
         */
        "x-token": string;
    };
    path?: never;
    query?: never;
    url: "/auth/onboard";
};

export type AuthOnboardStartErrors = {
    401: string;
    500: string;
};

export type AuthOnboardStartError = AuthOnboardStartErrors[keyof AuthOnboardStartErrors];

export type AuthOnboardStartResponses = {
    200: Array<Student>;
};

export type AuthOnboardStartResponse = AuthOnboardStartResponses[keyof AuthOnboardStartResponses];

export type AuthOnboardFinishData = {
    body: OnboardFinishRequest;
    path?: never;
    query?: never;
    url: "/auth/onboard";
};

export type AuthOnboardFinishErrors = {
    /**
     * The provided list of students does not match the existing list
     */
    400: string;
    401: string;
    500: string;
};

export type AuthOnboardFinishError = AuthOnboardFinishErrors[keyof AuthOnboardFinishErrors];

export type AuthOnboardFinishResponses = {
    200: unknown;
};

export type RosterSwipeData = {
    body: SwipeRequest;
    path?: never;
    query?: never;
    url: "/roster/swipe";
};

export type RosterSwipeErrors = {
    /**
     * The given hour type is not allowed at this time. See `/roster/allowed`.
     */
    400: string;
    /**
     * The provided TOTP is invalid
     */
    401: string;
    403: string;
    /**
     * No student with the given ID exists
     */
    404: string;
    500: string;
};

export type RosterSwipeError = RosterSwipeErrors[keyof RosterSwipeErrors];

export type RosterSwipeResponses = {
    200: SwipeResponse;
};

export type RosterSwipeResponse = RosterSwipeResponses[keyof RosterSwipeResponses];

export type RosterTotpData = {
    body: TotpRequest;
    path?: never;
    query?: never;
    url: "/roster/totp";
};

export type RosterTotpErrors = {
    401: string;
    403: string;
    500: string;
};

export type RosterTotpError = RosterTotpErrors[keyof RosterTotpErrors];

export type RosterTotpResponses = {
    200: TotpResponse;
};

export type RosterTotpResponse = RosterTotpResponses[keyof RosterTotpResponses];

export type RosterPresentQueryData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/roster/present";
};

export type RosterPresentQueryErrors = {
    401: string;
    403: string;
    500: string;
};

export type RosterPresentQueryError = RosterPresentQueryErrors[keyof RosterPresentQueryErrors];

export type RosterPresentQueryResponses = {
    200: PresentResponse;
};

export type RosterPresentQueryResponse = RosterPresentQueryResponses[keyof RosterPresentQueryResponses];

export type RosterPresentStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/roster/present/stream";
};

export type RosterPresentStreamErrors = {
    401: string;
    403: string;
    500: string;
};

export type RosterPresentStreamError = RosterPresentStreamErrors[keyof RosterPresentStreamErrors];

export type RosterPresentStreamResponses = {
    200: Array<PresentResponse>;
};

export type RosterPresentStreamResponse = RosterPresentStreamResponses[keyof RosterPresentStreamResponses];

export type RosterRecordDeleteData = {
    body: RosterDeleteRequest;
    path?: never;
    query?: never;
    url: "/roster";
};

export type RosterRecordDeleteErrors = {
    401: string;
    403: string;
    /**
     * Record with the given ID does not exist
     */
    404: string;
    500: string;
};

export type RosterRecordDeleteError = RosterRecordDeleteErrors[keyof RosterRecordDeleteErrors];

export type RosterRecordDeleteResponses = {
    200: Record;
};

export type RosterRecordDeleteResponse = RosterRecordDeleteResponses[keyof RosterRecordDeleteResponses];

export type RosterRecordQueryData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: "/roster";
};

export type RosterRecordQueryErrors = {
    401: string;
    403: string;
    /**
     * Record with the given ID does not exist
     */
    404: string;
    500: string;
};

export type RosterRecordQueryError = RosterRecordQueryErrors[keyof RosterRecordQueryErrors];

export type RosterRecordQueryResponses = {
    200: RosterQueryResponse;
};

export type RosterRecordQueryResponse = RosterRecordQueryResponses[keyof RosterRecordQueryResponses];

export type RosterRecordUpdateData = {
    body: PartialRecord;
    path?: never;
    query?: never;
    url: "/roster";
};

export type RosterRecordUpdateErrors = {
    /**
     * time_out is before or on a different day than time_in
     */
    400: string;
    401: string;
    403: string;
    /**
     * Record with the given ID does not exist
     */
    404: string;
    500: string;
};

export type RosterRecordUpdateError = RosterRecordUpdateErrors[keyof RosterRecordUpdateErrors];

export type RosterRecordUpdateResponses = {
    200: Record;
};

export type RosterRecordUpdateResponse = RosterRecordUpdateResponses[keyof RosterRecordUpdateResponses];

export type RosterRecordAddData = {
    body: RosterCreateRequest;
    path?: never;
    query?: never;
    url: "/roster";
};

export type RosterRecordAddErrors = {
    /**
     * time_out is before or on a different day than time_in
     */
    400: string;
    401: string;
    403: string;
    500: string;
};

export type RosterRecordAddError = RosterRecordAddErrors[keyof RosterRecordAddErrors];

export type RosterRecordAddResponses = {
    200: RosterCreateResponse;
};

export type RosterRecordAddResponse = RosterRecordAddResponses[keyof RosterRecordAddResponses];

export type RosterRecordStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/roster/stream";
};

export type RosterRecordStreamErrors = {
    401: string;
    403: string;
    /**
     * Record with the given ID does not exist
     */
    404: string;
    500: string;
};

export type RosterRecordStreamError = RosterRecordStreamErrors[keyof RosterRecordStreamErrors];

export type RosterRecordStreamResponses = {
    200: Array<ReplicationRecord>;
};

export type RosterRecordStreamResponse = RosterRecordStreamResponses[keyof RosterRecordStreamResponses];

export type RosterAllowedData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/roster/allowed";
};

export type RosterAllowedErrors = {
    401: string;
    500: string;
};

export type RosterAllowedError = RosterAllowedErrors[keyof RosterAllowedErrors];

export type RosterAllowedResponses = {
    200: Array<HourType>;
};

export type RosterAllowedResponse = RosterAllowedResponses[keyof RosterAllowedResponses];

export type StudentListData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/student";
};

export type StudentListErrors = {
    401: string;
    403: string;
    /**
     * No student with the given ID exists
     */
    404: string;
    500: string;
};

export type StudentListError = StudentListErrors[keyof StudentListErrors];

export type StudentListResponses = {
    200: StudentListResponse;
};

export type StudentListResponse2 = StudentListResponses[keyof StudentListResponses];

export type StudentAddData = {
    body: Student;
    path?: never;
    query?: never;
    url: "/student";
};

export type StudentAddErrors = {
    401: string;
    403: string;
    409: string;
    500: string;
};

export type StudentAddError = StudentAddErrors[keyof StudentAddErrors];

export type StudentAddResponses = {
    200: unknown;
};

export type StudentStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/student/stream";
};

export type StudentStreamErrors = {
    401: string;
    403: string;
    /**
     * No student with the given ID exists
     */
    404: string;
    500: string;
};

export type StudentStreamError = StudentStreamErrors[keyof StudentStreamErrors];

export type StudentStreamResponses = {
    200: Array<ReplicationStudent>;
};

export type StudentStreamResponse = StudentStreamResponses[keyof StudentStreamResponses];

export type StudentDeleteData = {
    body?: never;
    path: {
        id_hashed: string;
    };
    query?: never;
    url: "/student/{id_hashed}";
};

export type StudentDeleteErrors = {
    401: string;
    403: string;
    /**
     * No student with the given ID exists
     */
    404: string;
    500: string;
};

export type StudentDeleteError = StudentDeleteErrors[keyof StudentDeleteErrors];

export type StudentDeleteResponses = {
    200: Student;
};

export type StudentDeleteResponse = StudentDeleteResponses[keyof StudentDeleteResponses];

export type StudentQueryData = {
    body?: never;
    path: {
        id_hashed: string;
    };
    query?: never;
    url: "/student/{id_hashed}";
};

export type StudentQueryErrors = {
    401: string;
    403: string;
    /**
     * No student with the given ID exists
     */
    404: string;
    500: string;
};

export type StudentQueryError = StudentQueryErrors[keyof StudentQueryErrors];

export type StudentQueryResponses = {
    200: Student;
};

export type StudentQueryResponse = StudentQueryResponses[keyof StudentQueryResponses];

export type StudentUpdateData = {
    body: StudentUpdateRequest;
    path: {
        id_hashed: string;
    };
    query?: never;
    url: "/student/{id_hashed}";
};

export type StudentUpdateErrors = {
    401: string;
    403: string;
    /**
     * No student with the given ID exists
     */
    404: string;
    500: string;
};

export type StudentUpdateError = StudentUpdateErrors[keyof StudentUpdateErrors];

export type StudentUpdateResponses = {
    200: Student;
};

export type StudentUpdateResponse = StudentUpdateResponses[keyof StudentUpdateResponses];

export type StudentHoursData = {
    body?: never;
    path: {
        id_hashed: string;
    };
    query?: never;
    url: "/student/{id_hashed}/hours";
};

export type StudentHoursErrors = {
    404: string;
    500: string;
};

export type StudentHoursError = StudentHoursErrors[keyof StudentHoursErrors];

export type StudentHoursResponses = {
    200: StudentHoursResponse;
};

export type StudentHoursResponse2 = StudentHoursResponses[keyof StudentHoursResponses];

export type TelemetrySearchData = {
    body: TelemetryQueryRequest;
    path?: never;
    query?: never;
    url: "/telemetry/search";
};

export type TelemetrySearchErrors = {
    400: string;
    401: string;
    403: string;
    500: string;
};

export type TelemetrySearchError = TelemetrySearchErrors[keyof TelemetrySearchErrors];

export type TelemetrySearchResponses = {
    200: TelemetryResponse;
};

export type TelemetrySearchResponse = TelemetrySearchResponses[keyof TelemetrySearchResponses];

export type TelemetryGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/telemetry/{id}";
};

export type TelemetryGetErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type TelemetryGetError = TelemetryGetErrors[keyof TelemetryGetErrors];

export type TelemetryGetResponses = {
    200: TelemetryEvent;
};

export type TelemetryGetResponse = TelemetryGetResponses[keyof TelemetryGetResponses];

export type TelemetryFilterCreateData = {
    body?: EventTypeFilter;
    path?: never;
    query?: never;
    url: "/telemetry/stream/filter";
};

export type TelemetryFilterCreateErrors = {
    401: string;
    403: string;
    500: string;
};

export type TelemetryFilterCreateError = TelemetryFilterCreateErrors[keyof TelemetryFilterCreateErrors];

export type TelemetryFilterCreateResponses = {
    200: string;
};

export type TelemetryFilterCreateResponse = TelemetryFilterCreateResponses[keyof TelemetryFilterCreateResponses];

export type TelemetryFilterUpdateData = {
    body?: EventTypeFilter;
    path?: never;
    query: {
        id: string;
    };
    url: "/telemetry/stream/filter";
};

export type TelemetryFilterUpdateErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type TelemetryFilterUpdateError = TelemetryFilterUpdateErrors[keyof TelemetryFilterUpdateErrors];

export type TelemetryFilterUpdateResponses = {
    200: unknown;
};

export type TelemetryStreamData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: "/telemetry/stream";
};

export type TelemetryStreamErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type TelemetryStreamError = TelemetryStreamErrors[keyof TelemetryStreamErrors];

export type TelemetryStreamResponses = {
    200: Array<TelemetryEvent>;
};

export type TelemetryStreamResponse = TelemetryStreamResponses[keyof TelemetryStreamResponses];
