// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * AdminLogin
 */
export type AdminLogin = {
    id: string;
};

/**
 * AdminLogout
 */
export type AdminLogout = {
    id: string;
};

/**
 * Claims
 */
export type Claims = {
    sub: string;
    exp: number;
    perms: Permissions;
    k1e: string;
    username: string;
};

/**
 * Deletion_Record
 */
export type DeletionRecord = {
    pkey: string;
};

/**
 * Deletion_Student
 */
export type DeletionStudent = {
    pkey: string;
};

export type Event =
    | ({
        event?: "admin_login";
    } & EventAdminLogin)
    | ({
        event?: "admin_logout";
    } & EventAdminLogout)
    | ({
        event?: "student_add";
    } & EventStudentAdd)
    | ({
        event?: "student_delete";
    } & EventStudentDelete)
    | ({
        event?: "student_edit";
    } & EventStudentEdit)
    | ({
        event?: "record_add";
    } & EventRecordAdd)
    | ({
        event?: "record_delete";
    } & EventRecordDelete)
    | ({
        event?: "record_edit";
    } & EventRecordEdit)
    | ({
        event?: "student_login";
    } & EventStudentLogin)
    | ({
        event?: "student_logout";
    } & EventStudentLogout);

export type EventType =
    | "admin_login"
    | "admin_logout"
    | "student_add"
    | "student_delete"
    | "student_edit"
    | "record_add"
    | "record_delete"
    | "record_edit"
    | "student_login"
    | "student_logout";

export type EventAdminLogin = {
    event: "admin_login";
} & AdminLogin;

export type EventAdminLogout = {
    event: "admin_logout";
} & AdminLogout;

export type EventRecordAdd = {
    event: "record_add";
} & RecordAdd;

export type EventRecordDelete = {
    event: "record_delete";
} & RecordDelete;

export type EventRecordEdit = {
    event: "record_edit";
} & RecordEdit;

export type EventStudentAdd = {
    event: "student_add";
} & StudentAdd;

export type EventStudentDelete = {
    event: "student_delete";
} & StudentDelete;

export type EventStudentEdit = {
    event: "student_edit";
} & StudentEdit;

export type EventStudentLogin = {
    event: "student_login";
} & StudentLogin;

export type EventStudentLogout = {
    event: "student_logout";
} & StudentLogout;

export type HourType = "build" | "learning" | "demo" | "offseason";

/**
 * InviteRequest
 */
export type InviteRequest = {
    /**
     * The hashed student ID to associate with this invite, if any.
     */
    sid_hashed?: string;
    /**
     * Initial permissions to grant the user
     */
    permissions: Permissions & unknown;
};

/**
 * InviteResponse
 */
export type InviteResponse = {
    /**
     * Temporary key to encrypt k1. Do NOT share this
     */
    k2: string;
    /**
     * Invite token. This goes in the link
     */
    token: string;
};

/**
 * LoginFinishRequest
 */
export type LoginFinishRequest = {
    session: string;
    a: string;
    m1: string;
};

/**
 * LoginFinishResponse
 */
export type LoginFinishResponse = {
    jwt: string;
    claims: Claims;
};

/**
 * LoginStartResponse
 */
export type LoginStartResponse = {
    session: string;
    salt: string;
    b: string;
};

/**
 * OnboardFinishRequest
 */
export type OnboardFinishRequest = {
    students: Array<Student>;
    token: string;
    k1e: string;
    username: string;
    v: string;
    s: string;
};

/**
 * PartialRecord
 */
export type PartialRecord = {
    id: string;
    sid_hashed?: string;
    hour_type?: HourType;
    sign_in?: string;
    sign_out?: string | null;
};

/**
 * PartialStudent
 */
export type PartialStudent = {
    id_hashed: string;
    id?: string;
    first?: string;
    last?: string;
};

/**
 * Permissions
 */
export type Permissions = {
    student_add: boolean;
    student_view: boolean;
    student_edit: boolean;
    student_delete: boolean;
    admin_invite: boolean;
    admin_delete: boolean;
    telemetry: boolean;
    hours_view: boolean;
    hours_edit: boolean;
    roster: boolean;
    admin_edit: boolean;
};

/**
 * Record
 */
export type Record = {
    id: string;
    sid_hashed: string;
    hour_type: HourType;
    sign_in: string;
    sign_out?: string;
};

/**
 * RecordAdd
 */
export type RecordAdd = {
    admin_id: string;
    id: string;
    sid_hashed: string;
    hour_type: HourType;
    sign_in: string;
    sign_out?: string;
};

/**
 * RecordDelete
 */
export type RecordDelete = {
    admin_id: string;
    id: string;
    sid_hashed: string;
    hour_type: HourType;
    sign_in: string;
    sign_out?: string;
};

/**
 * RecordEdit
 */
export type RecordEdit = {
    admin_id: string;
    old: Record;
    id: string;
    sid_hashed?: string;
    hour_type?: HourType;
    sign_in?: string;
    sign_out?: string | null;
};

/**
 * RegisterFinishRequest
 */
export type RegisterFinishRequest = {
    token: string;
    k1e: string;
    username: string;
    v: string;
    s: string;
};

/**
 * RegisterStartResponse
 */
export type RegisterStartResponse = {
    k2: string;
};

export type ReplicationRecord =
    | ({
        operation?: "INSERT";
    } & ReplicationRecordInsert)
    | ({
        operation?: "UPDATE";
    } & ReplicationRecordUpdate)
    | ({
        operation?: "DELETE";
    } & ReplicationRecordDelete);

export type ReplicationRecordDelete = {
    operation: "DELETE";
} & DeletionRecord;

export type ReplicationRecordInsert = {
    operation: "INSERT";
} & Record;

export type ReplicationRecordUpdate = {
    operation: "UPDATE";
} & PartialRecord;

export type ReplicationStudent =
    | ({
        operation?: "INSERT";
    } & ReplicationStudentInsert)
    | ({
        operation?: "UPDATE";
    } & ReplicationStudentUpdate)
    | ({
        operation?: "DELETE";
    } & ReplicationStudentDelete);

export type ReplicationStudentDelete = {
    operation: "DELETE";
} & DeletionStudent;

export type ReplicationStudentInsert = {
    operation: "INSERT";
} & Student;

export type ReplicationStudentUpdate = {
    operation: "UPDATE";
} & PartialStudent;

/**
 * RosterCreateRequest
 */
export type RosterCreateRequest = {
    sid_hashed: string;
    kind: HourType;
    time_in: string;
    /**
     * Must be after and on the same day as time_in (in server's local time)
     */
    time_out?: string;
};

/**
 * RosterCreateResponse
 */
export type RosterCreateResponse = {
    entry_id: string;
};

/**
 * RosterDeleteRequest
 */
export type RosterDeleteRequest = {
    entry_id: string;
};

/**
 * RosterGetMany
 */
export type RosterGetMany = {
    records: {
        [key: string]: Record;
    };
};

export type RosterGetResponse =
    | ({
        quantity?: "Many";
    } & RosterGetResponseMany)
    | ({
        quantity?: "One";
    } & RosterGetResponseOne);

export type RosterGetResponseMany = {
    quantity: "Many";
} & RosterGetMany;

export type RosterGetResponseOne = {
    quantity: "One";
} & Record;

/**
 * Student
 */
export type Student = {
    id: string;
    first: string;
    last: string;
    id_hashed: string;
};

/**
 * StudentAdd
 */
export type StudentAdd = {
    admin_id: string;
    id: string;
    first: string;
    last: string;
    id_hashed: string;
};

/**
 * StudentAddRequest
 */
export type StudentAddRequest = {
    sid_hashed: string;
    student_id: string;
    first: string;
    last: string;
};

/**
 * StudentDelete
 */
export type StudentDelete = {
    admin_id: string;
    id: string;
    first: string;
    last: string;
    id_hashed: string;
};

/**
 * StudentEdit
 */
export type StudentEdit = {
    admin_id: string;
    old: Student;
    id_hashed: string;
    id?: string;
    first?: string;
    last?: string;
};

/**
 * StudentHoursResponse
 */
export type StudentHoursResponse = {
    build: number;
    learning: number;
    demo: number;
    offseason: number;
};

/**
 * StudentListResponse
 */
export type StudentListResponse = {
    students: Array<Student>;
};

/**
 * StudentLogin
 */
export type StudentLogin = {
    sid_hashed: string;
    record_id: string;
    admin_id: string;
};

/**
 * StudentLogout
 */
export type StudentLogout = {
    sid_hashed: string;
    record_id: string;
    admin_id: string;
};

/**
 * StudentUpdateRequest
 */
export type StudentUpdateRequest = {
    id?: string;
    first?: string;
    last?: string;
};

export type SwipeAction = "Login" | "Logout" | "Denied";

/**
 * SwipeQueryResponse
 */
export type SwipeQueryResponse = {
    present: Array<string>;
    absent: Array<string>;
};

/**
 * SwipeRequest
 */
export type SwipeRequest = {
    sid_hashed: string;
    kind: HourType;
    force?: boolean;
};

/**
 * SwipeResponse
 */
export type SwipeResponse = {
    action: SwipeAction;
};

/**
 * TelemetryEvent
 */
export type TelemetryEvent = {
    id: string;
    event: Event;
    timestamp: string;
};

/**
 * TelemetryResponse
 */
export type TelemetryResponse = {
    events: Array<TelemetryEvent>;
};

export type AuthLoginStartData = {
    body?: never;
    path?: never;
    query: {
        username: string;
    };
    url: "/auth/login";
};

export type AuthLoginStartErrors = {
    500: string;
};

export type AuthLoginStartError = AuthLoginStartErrors[keyof AuthLoginStartErrors];

export type AuthLoginStartResponses = {
    200: LoginStartResponse;
};

export type AuthLoginStartResponse = AuthLoginStartResponses[keyof AuthLoginStartResponses];

export type AuthLoginFinishData = {
    body: LoginFinishRequest;
    path?: never;
    query?: never;
    url: "/auth/login";
};

export type AuthLoginFinishErrors = {
    400: string;
    401: string;
    500: string;
};

export type AuthLoginFinishError = AuthLoginFinishErrors[keyof AuthLoginFinishErrors];

export type AuthLoginFinishResponses = {
    200: LoginFinishResponse;
};

export type AuthLoginFinishResponse = AuthLoginFinishResponses[keyof AuthLoginFinishResponses];

export type AuthInviteData = {
    body: InviteRequest;
    path?: never;
    query?: never;
    url: "/auth/invite";
};

export type AuthInviteErrors = {
    401: string;
    403: string;
    500: string;
};

export type AuthInviteError = AuthInviteErrors[keyof AuthInviteErrors];

export type AuthInviteResponses = {
    200: InviteResponse;
};

export type AuthInviteResponse = AuthInviteResponses[keyof AuthInviteResponses];

export type AuthRegisterStartData = {
    body?: never;
    path?: never;
    query: {
        key: string;
    };
    url: "/auth/register";
};

export type AuthRegisterStartErrors = {
    401: string;
    500: string;
};

export type AuthRegisterStartError = AuthRegisterStartErrors[keyof AuthRegisterStartErrors];

export type AuthRegisterStartResponses = {
    200: RegisterStartResponse;
};

export type AuthRegisterStartResponse = AuthRegisterStartResponses[keyof AuthRegisterStartResponses];

export type AuthRegisterFinishData = {
    body: RegisterFinishRequest;
    path?: never;
    query?: never;
    url: "/auth/register";
};

export type AuthRegisterFinishErrors = {
    400: string;
    401: string;
    500: string;
};

export type AuthRegisterFinishError = AuthRegisterFinishErrors[keyof AuthRegisterFinishErrors];

export type AuthRegisterFinishResponses = {
    200: unknown;
};

export type AuthOnboardTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/auth/onboard/token";
};

export type AuthOnboardTokenErrors = {
    401: string;
    500: string;
};

export type AuthOnboardTokenError = AuthOnboardTokenErrors[keyof AuthOnboardTokenErrors];

export type AuthOnboardTokenResponses = {
    200: unknown;
};

export type AuthOnboardStartData = {
    body?: never;
    headers: {
        /**
         * The setup token obtained from /auth/onboard/token
         */
        "x-token": string;
    };
    path?: never;
    query?: never;
    url: "/auth/onboard";
};

export type AuthOnboardStartErrors = {
    401: string;
    500: string;
};

export type AuthOnboardStartError = AuthOnboardStartErrors[keyof AuthOnboardStartErrors];

export type AuthOnboardStartResponses = {
    200: Array<Student>;
};

export type AuthOnboardStartResponse = AuthOnboardStartResponses[keyof AuthOnboardStartResponses];

export type AuthOnboardFinishData = {
    body: OnboardFinishRequest;
    path?: never;
    query?: never;
    url: "/auth/onboard";
};

export type AuthOnboardFinishErrors = {
    400: string;
    401: string;
    500: string;
};

export type AuthOnboardFinishError = AuthOnboardFinishErrors[keyof AuthOnboardFinishErrors];

export type AuthOnboardFinishResponses = {
    200: unknown;
};

export type RosterSwipesQueryData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/roster/swipe";
};

export type RosterSwipesQueryErrors = {
    401: string;
    403: string;
    500: string;
};

export type RosterSwipesQueryError = RosterSwipesQueryErrors[keyof RosterSwipesQueryErrors];

export type RosterSwipesQueryResponses = {
    200: SwipeQueryResponse;
};

export type RosterSwipesQueryResponse = RosterSwipesQueryResponses[keyof RosterSwipesQueryResponses];

export type RosterSwipeData = {
    body: SwipeRequest;
    path?: never;
    query?: never;
    url: "/roster/swipe";
};

export type RosterSwipeErrors = {
    400: string;
    401: string;
    403: string;
    500: string;
};

export type RosterSwipeError = RosterSwipeErrors[keyof RosterSwipeErrors];

export type RosterSwipeResponses = {
    200: SwipeResponse;
};

export type RosterSwipeResponse = RosterSwipeResponses[keyof RosterSwipeResponses];

export type RosterSwipesStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/roster/swipe/stream";
};

export type RosterSwipesStreamErrors = {
    401: string;
    403: string;
    500: string;
};

export type RosterSwipesStreamError = RosterSwipesStreamErrors[keyof RosterSwipesStreamErrors];

export type RosterSwipesStreamResponses = {
    200: Array<SwipeQueryResponse>;
};

export type RosterSwipesStreamResponse = RosterSwipesStreamResponses[keyof RosterSwipesStreamResponses];

export type RosterRecordDeleteData = {
    body: RosterDeleteRequest;
    path?: never;
    query?: never;
    url: "/roster";
};

export type RosterRecordDeleteErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type RosterRecordDeleteError = RosterRecordDeleteErrors[keyof RosterRecordDeleteErrors];

export type RosterRecordDeleteResponses = {
    200: Record;
};

export type RosterRecordDeleteResponse = RosterRecordDeleteResponses[keyof RosterRecordDeleteResponses];

export type RosterRecordQueryData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: "/roster";
};

export type RosterRecordQueryErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type RosterRecordQueryError = RosterRecordQueryErrors[keyof RosterRecordQueryErrors];

export type RosterRecordQueryResponses = {
    200: RosterGetResponse;
};

export type RosterRecordQueryResponse = RosterRecordQueryResponses[keyof RosterRecordQueryResponses];

export type RosterRecordUpdateData = {
    body: PartialRecord;
    path?: never;
    query?: never;
    url: "/roster";
};

export type RosterRecordUpdateErrors = {
    400: string;
    401: string;
    403: string;
    404: string;
    500: string;
};

export type RosterRecordUpdateError = RosterRecordUpdateErrors[keyof RosterRecordUpdateErrors];

export type RosterRecordUpdateResponses = {
    200: Record;
};

export type RosterRecordUpdateResponse = RosterRecordUpdateResponses[keyof RosterRecordUpdateResponses];

export type RosterRecordAddData = {
    body: RosterCreateRequest;
    path?: never;
    query?: never;
    url: "/roster";
};

export type RosterRecordAddErrors = {
    400: string;
    401: string;
    403: string;
    500: string;
};

export type RosterRecordAddError = RosterRecordAddErrors[keyof RosterRecordAddErrors];

export type RosterRecordAddResponses = {
    200: RosterCreateResponse;
};

export type RosterRecordAddResponse = RosterRecordAddResponses[keyof RosterRecordAddResponses];

export type RosterRecordStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/roster/stream";
};

export type RosterRecordStreamErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type RosterRecordStreamError = RosterRecordStreamErrors[keyof RosterRecordStreamErrors];

export type RosterRecordStreamResponses = {
    200: Array<ReplicationRecord>;
};

export type RosterRecordStreamResponse = RosterRecordStreamResponses[keyof RosterRecordStreamResponses];

export type StudentListData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/student";
};

export type StudentListErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type StudentListError = StudentListErrors[keyof StudentListErrors];

export type StudentListResponses = {
    200: StudentListResponse;
};

export type StudentListResponse2 = StudentListResponses[keyof StudentListResponses];

export type StudentAddData = {
    body: StudentAddRequest;
    path?: never;
    query?: never;
    url: "/student";
};

export type StudentAddErrors = {
    401: string;
    403: string;
    500: string;
};

export type StudentAddError = StudentAddErrors[keyof StudentAddErrors];

export type StudentAddResponses = {
    200: unknown;
};

export type StudentStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/student/stream";
};

export type StudentStreamErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type StudentStreamError = StudentStreamErrors[keyof StudentStreamErrors];

export type StudentStreamResponses = {
    200: Array<ReplicationStudent>;
};

export type StudentStreamResponse = StudentStreamResponses[keyof StudentStreamResponses];

export type StudentDeleteData = {
    body?: never;
    path: {
        id_hashed: string;
    };
    query?: never;
    url: "/student/{id_hashed}";
};

export type StudentDeleteErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type StudentDeleteError = StudentDeleteErrors[keyof StudentDeleteErrors];

export type StudentDeleteResponses = {
    200: Student;
};

export type StudentDeleteResponse = StudentDeleteResponses[keyof StudentDeleteResponses];

export type StudentQueryData = {
    body?: never;
    path: {
        id_hashed: string;
    };
    query?: never;
    url: "/student/{id_hashed}";
};

export type StudentQueryErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type StudentQueryError = StudentQueryErrors[keyof StudentQueryErrors];

export type StudentQueryResponses = {
    200: Student;
};

export type StudentQueryResponse = StudentQueryResponses[keyof StudentQueryResponses];

export type StudentUpdateData = {
    body: StudentUpdateRequest;
    path: {
        id_hashed: string;
    };
    query?: never;
    url: "/student/{id_hashed}";
};

export type StudentUpdateErrors = {
    401: string;
    403: string;
    404: string;
    500: string;
};

export type StudentUpdateError = StudentUpdateErrors[keyof StudentUpdateErrors];

export type StudentUpdateResponses = {
    200: Student;
};

export type StudentUpdateResponse = StudentUpdateResponses[keyof StudentUpdateResponses];

export type StudentHoursData = {
    body?: never;
    path: {
        id_hashed: string;
    };
    query?: never;
    url: "/student/{id_hashed}/hours";
};

export type StudentHoursErrors = {
    500: string;
};

export type StudentHoursError = StudentHoursErrors[keyof StudentHoursErrors];

export type StudentHoursResponses = {
    200: StudentHoursResponse;
};

export type StudentHoursResponse2 = StudentHoursResponses[keyof StudentHoursResponses];

export type TelemetryGetData = {
    body?: never;
    path?: never;
    query: {
        count: number;
        skip: number;
    };
    url: "/telemetry";
};

export type TelemetryGetErrors = {
    400: string;
    401: string;
    403: string;
    500: string;
};

export type TelemetryGetError = TelemetryGetErrors[keyof TelemetryGetErrors];

export type TelemetryGetResponses = {
    200: TelemetryResponse;
};

export type TelemetryGetResponse = TelemetryGetResponses[keyof TelemetryGetResponses];

export type TelemetryStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/telemetry/stream";
};

export type TelemetryStreamErrors = {
    400: string;
    401: string;
    403: string;
    500: string;
};

export type TelemetryStreamError = TelemetryStreamErrors[keyof TelemetryStreamErrors];

export type TelemetryStreamResponses = {
    200: Array<TelemetryEvent>;
};

export type TelemetryStreamResponse = TelemetryStreamResponses[keyof TelemetryStreamResponses];

export type TelemetryQueryData = {
    body?: never;
    path: {
        event_type: EventType;
    };
    query: {
        count: number;
        skip: number;
    };
    url: "/telemetry/{event_type}";
};

export type TelemetryQueryErrors = {
    400: string;
    401: string;
    403: string;
    500: string;
};

export type TelemetryQueryError = TelemetryQueryErrors[keyof TelemetryQueryErrors];

export type TelemetryQueryResponses = {
    200: TelemetryResponse;
};

export type TelemetryQueryResponse = TelemetryQueryResponses[keyof TelemetryQueryResponses];
