name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
          
      - name: Cache target directory
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-rust-cache

      - name: Build
        run: cargo build --release
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Docker image
        run: docker build -t onlycs/attendance .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push onlycs/attendance

      - name: Deploy on SSH server
        uses: appleboy/ssh-action@master
        with:
          host: redlap
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.SSH_HOST }}
          proxy_username: ${{ secrets.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/attendance
            docker-compose down
            docker-compose pull
            docker-compose up -d