name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.vue"
      - "**.ts"
      - ".github/workflows/deploy.yaml"
      - "**Dockerfile"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Google Cloud
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WLIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA }}
          access_token_lifetime: 600s

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Restore build cache
        uses: actions/cache/restore@v4
        id: build-cache
        with:
          path: |
            src-api/target
            src-crypto/target
            src-macro/target
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-build-

      - name: Set up Rust
        if: steps.build-cache.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-11-15
          targets: wasm32-unknown-unknown
          components: rustfmt

      - name: Write to .env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > src-api/.env

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Check if sqlx CLI is cached
        id: checkfile
        run: |
          if [ -f "$HOME/.cargo/bin/sqlx" ]; then echo "exists=true" >> $GITHUB_OUTPUT
          else echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install sqlx CLI
        if: steps.checkfile.outputs.exists == 'false'
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Run database migrations
        run: sqlx migrate run
        working-directory: src-api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install dependencies and run postinstall
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > src-api/.env
          bun i
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build API
        working-directory: src-api
        run: cargo build --release --locked --no-default-features
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build API image
        run: docker build . -t onlycs/attendance:api -f Dockerfile.api

      - name: Generate static site
        run: bun generate

      - name: Build API (include static assets)
        working-directory: src-api
        run: cargo build --release --locked
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build standard image
        run: docker build . -t onlycs/attendance:latest

      - name: Push Docker images
        run: |
          docker push onlycs/attendance:api
          docker push onlycs/attendance:latest

      - name: Regenerate frontend for ourselves
        run: |
          rm -rf .output
          echo "NUXT_PUBLIC_API_URL=${{ secrets.API_URL }}" > .env
          bun generate
        env:
          API_URL: ${{ secrets.API_URL }}

      - name: Deploy API to GCE
        run: |
          gcloud compute ssh attendance-vm \
            --zone=us-central1-a \
            --tunnel-through-iap \
            --command="
              sudo docker pull onlycs/attendance:api &&
              sudo docker stop attendance || true &&
              sudo docker rm attendance || true &&
              sudo docker run -d \
                --name attendance \
                --restart always \
                --network=attendance-net \
                -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
                -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
                -p 8080:8080 \
                onlycs/attendance:api
            "

      - name: Deploy Static to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RIVER_WAVE_445602_N7 }}
          channelId: live
          projectId: ${{ secrets.GCP_PROJECT_ID }}

      - name: Save Build cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            src-api/target
            src-crypto/target
            src-macro/target
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/package-lock.json') }}
