name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.vue"
      - "**.ts"
      - ".github/workflows/deploy.yaml"
      - "**Dockerfile"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore build cache
        uses: actions/cache/restore@v4
        id: build-cache
        with:
          path: |
            src-api/target
            src-crypto/target
            src-macro/target
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-build-

      - name: Set up Rust
        if: steps.build-cache.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-11-15
          targets: wasm32-unknown-unknown
          components: rustfmt

      - name: Write to .env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > src-api/.env

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Check if sqlx CLI is cached
        id: checkfile
        run: |
          if [ -f "$HOME/.cargo/bin/sqlx" ]; then echo "exists=true" >> $GITHUB_OUTPUT
          else echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install sqlx CLI
        if: steps.checkfile.outputs.exists == 'false'
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Run database migrations
        run: sqlx migrate run
        working-directory: src-api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install dependencies and run postinstall
        run: bun i
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Generate static site
        run: bun generate

      - name: Build API
        working-directory: src-api
        run: cargo build --release --locked
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build standard image
        run: docker build . -t ghcr.io/${{ github.repository }}:latest

      - name: Push Docker images
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Save Build cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            src-api/target
            src-crypto/target
            src-macro/target
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/package-lock.json') }}
